language: go
go:
  - 1.12.x
env:
  - GO111MODULE=on
os:
  - linux	
  - osx
  - windows
install: true
script:
  - go vet ./...
  - go test -v -mod=vendor
  - go test -v -mod=vendor ./keyholder
  - go install -mod=vendor ./...
